from __future__ import annotations

from transleg.domain.models import ReportName, ReportSpec

DOCS_EMITIDOS_MAP = {
    "Tipo": "tipo",
    "Filial Origem": "filial_origem",
    "Emissor": "emissor",
    "Documento": "documento",
    "Serie": "serie",
    "Filial Destino": "filial_destino",
    "Data Emissão": "data_emissao",
    "Prazo Entrega": "prazo_entrega",
    "Meta Entrega": "meta_entrega",
    "Status": "status",
    "Descrição Status": "descricao_status",
    "Data Entrega": "data_entrega",
    "Recebedor Mercadoria": "recebedor_mercadoria",
    "RG Recebedor": "rg_recebedor",
    "Tipo de Frete": "tipo_de_frete",
    "CNPJ Coleta": "cnpj_coleta",
    "Nome": "nome_coleta",
    "Cidade": "cidade_coleta",
    "UF": "uf_coleta",
    "CNPJ Remetente": "cnpj_remetente",
    "Nome.1": "nome_remetente",
    "Cidade.1": "cidade_remetente",
    "UF.1": "uf_remetente",
    "CNPJ Destinatario": "cnpj_destinatario",
    "Nome.2": "nome_destinatario",
    "Cidade.2": "cidade_destinatario",
    "UF.2": "uf_destinatario",
    "CEP Destino": "cep_destino",
    "CNPJ Entrega": "cnpj_entrega",
    "Nome.3": "nome_entrega",
    "Cidade.3": "cidade_entrega",
    "UF.3": "uf_entrega",
    "CEP Destino.1": "cep_destino_entrega",
    "CNPJ Redespacho": "cnpj_redespacho",
    "Nome.4": "nome_redespacho",
    "Cidade.4": "cidade_redespacho",
    "UF.4": "uf_redespacho",
    "CNPJ Pagador": "cnpj_pagador",
    "Nome.5": "nome_pagador",
    "Notas Fiscais/Serie": "notas_fiscais_serie",
    "Volumes": "volumes",
    "Valor Mercadoria": "valor_mercadoria",
    "Peso": "peso",
    "Peso Cubado": "peso_cubado",
    "Metr. Cub.": "metr_cub",
    "Frete Peso": "frete_peso",
    "Frete Valor": "frete_valor",
    "Valor do CAT": "valor_do_cat",
    "Valor Despacho": "valor_despacho",
    "Valor Pedagio": "valor_pedagio",
    "GRIS": "gris",
    "Seguro": "seguro",
    "Taxas Col./Ent.": "taxas_col_ent",
    "TDE": "tde",
    "TRT": "trt",
    "Outras Taxas": "outras_taxas",
    "Valor do Frete": "valor_do_frete",
    "Desconto": "desconto",
    "Valor Liquido Documento": "valor_liquido_documento",
    "Frete Cortesia": "frete_cortesia",
    "Valor Frete Parceiro": "valor_frete_parceiro",
    "Doc Redesp Parceiro": "doc_redesp_parceiro",
    "Base de Calculo ICMS": "base_de_calculo_icms",
    "Valor Icms": "valor_icms",
    "Aliq. de Icms": "aliq_de_icms",
    "Tipo de ICMS": "tipo_de_icms",
    "CFOP": "cfop",
    "Chave CT-e": "chave_cte",
    "Natureza": "natureza",
    "Especie": "especie",
    "Produto Calc.": "produto_calc",
    "Tipo Veículo Calc.": "tipo_veiculo_calc",
    "Quimico": "quimico",
    "Placa Cavalo": "placa_cavalo",
    "Placa Carreta": "placa_carreta",
    "Motorista": "motorista",
    "Manifesto(s)": "manifestos",
    "Romaneios": "romaneios",
    "Documento Original": "documento_original",
    "Filial Doc Original": "filial_doc_original",
    "Serie.1": "serie_doc_original",
    "Tipo Complementar": "tipo_complementar",
    "Numero DT": "numero_dt",
    "Filial Cotacao": "filial_cotacao",
    "Nº Cotacao": "numero_cotacao",
    "Observacao": "observacao",
    "Obs. de Ocorrencia": "obs_de_ocorrencia",
    "Vendedor": "vendedor",
    "Fatura": "fatura",
    "Data Vencimento": "data_vencimento",
    "Data Prorrogação": "data_prorrogacao",
    "Data Pagamento": "data_pagamento",
    "Valor recebido Fatura": "valor_recebido_fatura",
    "Banco Credito": "banco_credito",
    "Status Pag": "status_pag",
    "Data Pagamento Frete A Vista": "data_pagamento_frete_a_vista",
    "Valor recebido Frete A Vista": "valor_recebido_frete_a_vista",
    "Banco Credito Frete A Vista": "banco_credito_frete_a_vista",
    "Status Pag Frete A Vista": "status_pag_frete_a_vista",
    "Setor Entrega": "setor_entrega",
}

FATURAS_RECEBIDAS_MAP = {
    "Cliente": "cliente",
    "Nome": "nome",
    "Filial": "filial",
    "Duplicata": "duplicata",
    "Numero Boleto": "numero_boleto",
    "Data Emissão": "data_emissao",
    "Data Vencimento": "data_vencimento",
    "Data Recebimento": "data_recebimento",
    "Data Credito": "data_credito",
    "Data Baixa": "data_baixa",
    "Codigo Banco": "codigo_banco",
    "Nome Banco": "nome_banco",
    "Valor Total": "valor_total",
    "Multa": "multa",
    "Juros": "juros",
    "Desconto": "desconto",
    "Tarifa Bancária": "tarifa_bancaria",
    "Valor Recebido": "valor_recebido",
    "Status": "status",
    "Descrição": "descricao",
    "Cód Banco Crédito": "cod_banco_credito",
    "Nome Banco Crédito": "nome_banco_credito",
    "Tipo Pagamento": "tipo_pagamento",
    "Número Depósito": "numero_deposito",
    "Número Cheque": "numero_cheque",
    "Banco Cheque": "banco_cheque",
    "Bom Para": "bom_para",
    "Observação": "observacao",
}

TITULOS_PAGOS_PAGAR_MAP = {
    "Status": "status",
    "Nr Lançamento": "nr_lancamento",
    "Data Lançamento": "data_lancamento",
    "Data Emissão": "data_emissao",
    "Data Competência": "data_competencia",
    "Data de Vencimento": "data_de_vencimento",
    "Data Previsão de Pagamento": "data_previsao_de_pagamento",
    "Data Baixa": "data_baixa",
    "Conciliado?": "conciliado",
    "Data Conciliação": "data_conciliacao",
    "Parcela": "parcela",
    "Valor Original": "valor_original",
    "Juros": "juros",
    "Multa": "multa",
    "Desc. Imposto": "desc_imposto",
    "Desc. Baixa": "desc_baixa",
    "Total Pago": "total_pago",
    "Nr. Titulo": "nr_titulo",
    "NF-e ou NFS-e": "nfe_ou_nfse",
    "Nosso Nº Boleto/Doc": "nosso_numero_boleto_doc",
    "Nome Fornecedor": "nome_fornecedor",
    "Tipo de Documento": "tipo_de_documento",
    "Portador": "portador",
    "Numero Cheque": "numero_cheque",
    "Conta/Banco Caixa": "conta_banco_caixa",
    "Agencia": "agencia",
    "Conta": "conta",
    "Departamento": "departamento",
    "Centro de Custo": "centro_de_custo",
    "SubCusto": "subcusto",
    "Data Cancelamento": "data_cancelamento",
    "Usuario Cancelamento": "usuario_cancelamento",
    "Motivo Cancelamento": "motivo_cancelamento",
    "Histórico": "historico",
    "Valor Rateado": "valor_rateado",
    "OBS Rateio de custo": "obs_rateio_de_custo",
}

LANCAMENTOS_MANUAIS_MAP = {
    "Nr Lancto": "nr_lancto",
    "Centro Custo": "centro_custo",
    "Sub Custo": "sub_custo",
    "Data Lancto": "data_lancto",
    "Valor": "valor",
    "Tipo Operacao": "tipo_operacao",
    "Dep. Identificado?": "dep_identificado",
    "Identificação Dep.": "identificacao_dep",
    "Banco Origem": "banco_origem",
    "Banco Destino": "banco_destino",
    "Historico": "historico",
    "Fatura(s) Atrelada(s)": "faturas_atreladas",
}

REPORT_SPECS = {
    ReportName.ISSUED_DOCUMENTS: ReportSpec(
        report_name=ReportName.ISSUED_DOCUMENTS,
        display_name="Documentos Emitidos",
        menu_module_id="lnkModuloOperacional",
        report_code_id="155",
        report_link_fragment="/RGDocsEmitidosGeral/RGDocsEmitidosGeral",
        monitor_description="REL. DE DOCS EMITIDOS GERAL",
        file_prefix="Relat_Docs_Emitidos_",
        table_name="public.docs_emitidos",
        conflict_columns=("filial_origem", "serie", "documento"),
        column_mapping=DOCS_EMITIDOS_MAP,
        clear_fields=("txtFilialEmissao", "txtFilialDestino"),
        click_fields=("txtFilialEmissaoDesc", "txtFilialDestinoDesc", "txtCliente", "txtClienteDesc"),
        date_columns=(
            "data_emissao",
            "prazo_entrega",
            "meta_entrega",
            "data_entrega",
            "data_vencimento",
            "data_prorrogacao",
            "data_pagamento",
            "data_pagamento_frete_a_vista",
        ),
        numeric_br_columns=(
            "valor_mercadoria",
            "peso",
            "peso_cubado",
            "metr_cub",
            "frete_peso",
            "frete_valor",
            "valor_do_cat",
            "valor_despacho",
            "valor_pedagio",
            "gris",
            "seguro",
            "taxas_col_ent",
            "tde",
            "trt",
            "outras_taxas",
            "valor_do_frete",
            "desconto",
            "valor_liquido_documento",
            "valor_frete_parceiro",
            "base_de_calculo_icms",
            "valor_icms",
            "aliq_de_icms",
            "valor_recebido_fatura",
            "valor_recebido_frete_a_vista",
        ),
        integer_ranges={
            "filial_origem": (-2147483648, 2147483647),
            "serie": (-2147483648, 2147483647),
            "filial_destino": (-2147483648, 2147483647),
            "volumes": (-2147483648, 2147483647),
            "cfop": (-2147483648, 2147483647),
            "filial_doc_original": (-2147483648, 2147483647),
            "serie_doc_original": (-2147483648, 2147483647),
            "filial_cotacao": (-2147483648, 2147483647),
            "numero_cotacao": (-2147483648, 2147483647),
            "banco_credito": (-2147483648, 2147483647),
            "banco_credito_frete_a_vista": (-2147483648, 2147483647),
        },
    ),
    ReportName.RECEIVED_INVOICES: ReportSpec(
        report_name=ReportName.RECEIVED_INVOICES,
        display_name="Faturas Recebidas",
        menu_module_id="lnkModuloFaturamento",
        report_code_id="271",
        report_link_fragment="/FaturasRecebidas/FaturasRecebidas",
        monitor_description="REL. DE FATURAS RECEBIDAS",
        file_prefix="FaturasRecebidas_",
        table_name="public.faturas_recebidas",
        conflict_columns=("duplicata",),
        column_mapping=FATURAS_RECEBIDAS_MAP,
        clear_fields=("txtFilialEmissao",),
        click_fields=(
            "txtFilialCobranca",
            "txtFilialCobrancaDesc",
            "txtBanco",
            "txtBancoDesc",
            "txtCliente",
            "txtClienteDesc",
            "txtBancoReb",
            "txtBancoRebDesc",
        ),
        radio_button_id="rdbBaixa",
        date_columns=(
            "data_emissao",
            "data_vencimento",
            "data_recebimento",
            "data_credito",
            "data_baixa",
            "bom_para",
        ),
        numeric_br_columns=(
            "valor_total",
            "multa",
            "juros",
            "desconto",
            "tarifa_bancaria",
            "valor_recebido",
        ),
        integer_ranges={"numero_cheque": (-9223372036854775808, 9223372036854775807)},
    ),
    ReportName.PAYABLE_TITLES: ReportSpec(
        report_name=ReportName.PAYABLE_TITLES,
        display_name="Titulos Pagos/Pagar",
        menu_module_id="lnkModuloFinanceiro",
        report_code_id="319",
        report_link_fragment="/TituloPagoAPagar/TituloPagoAPagar",
        monitor_description="TITULOS PAGOS/PAGAR",
        file_prefix="TitulosPagosPagar_",
        table_name="public.titulos_pagos_pagar",
        conflict_columns=("nr_lancamento", "parcela", "data_previsao_de_pagamento"),
        column_mapping=TITULOS_PAGOS_PAGAR_MAP,
        click_fields=(
            "txtFilialCobranca",
            "txtFilialCobrancaDesc",
            "txtFornecedor",
            "txtNomeFornecedor",
            "txtTpDoc",
            "txtTpDocDesc",
            "txtCentroCusto",
            "txtCentroCustoDesc",
            "txtSubCusto",
            "txtSubcustoDesc",
            "txtPortador",
            "txtPortadorNome",
            "txtBanco",
            "txtBancoDesc",
        ),
        select_fields={"ddlPesquisadata": "previsao"},
        date_columns=(
            "data_lancamento",
            "data_emissao",
            "data_competencia",
            "data_de_vencimento",
            "data_previsao_de_pagamento",
            "data_baixa",
            "data_conciliacao",
            "data_cancelamento",
        ),
        numeric_br_columns=(
            "valor_original",
            "juros",
            "multa",
            "desc_imposto",
            "desc_baixa",
            "total_pago",
            "valor_rateado",
        ),
        integer_ranges={
            "nr_lancamento": (-9223372036854775808, 9223372036854775807),
            "nr_titulo": (-9223372036854775808, 9223372036854775807),
            "numero_cheque": (-9223372036854775808, 9223372036854775807),
            "centro_de_custo": (-9223372036854775808, 9223372036854775807),
            "subcusto": (-9223372036854775808, 9223372036854775807),
        },
    ),
    ReportName.MANUAL_RELEASES: ReportSpec(
        report_name=ReportName.MANUAL_RELEASES,
        display_name="Lancamentos e Transferencias",
        menu_module_id="lnkModuloFinanceiro",
        report_code_id="318",
        report_link_fragment="/RelatLancaTransf/RelatLancaTransf",
        monitor_description="LANÇAMENTOS E TRANSFERÊNCIAS",
        file_prefix="LanctoTransf_",
        table_name="public.lancamentos_manuais",
        conflict_columns=("nr_lancto", "data_lancto", "valor"),
        column_mapping=LANCAMENTOS_MANUAIS_MAP,
        clear_fields=("txtFilialOrigem",),
        click_fields=("txtCentroCusto", "txtCentroCustoDesc", "txtSubCusto", "txtSubcustoDesc"),
        select_fields={"ddlPesquisaTp": "A"},
        tail_rows_to_drop=4,
        date_columns=("data_lancto",),
        numeric_br_columns=("valor",),
        integer_ranges={
            "nr_lancto": (-9223372036854775808, 9223372036854775807),
            "centro_custo": (-9223372036854775808, 9223372036854775807),
            "sub_custo": (-9223372036854775808, 9223372036854775807),
        },
    ),
}


def get_report_spec(report_name: ReportName) -> ReportSpec:
    return REPORT_SPECS[report_name]


def list_report_specs() -> list[ReportSpec]:
    return list(REPORT_SPECS.values())

